### ISSUE TITLE
Bad request (400) when using the search API

### ISSUE THREAD

**Issue by j-martin** [clubhouse/clubhouse-lib#29]
I am using 0.4.0 and I am trying to use the `search/stories` endpoint, but I am getting a 400 when calling the endpoint with clubhouse-lib. If I use curl or my own python lib (based on requests) everything works fine. The only difference I can see from the request is that the `Content-Length` header is not set by clubhouse-lib. I might be a red herring. 

`client.getResource('search/stories', { query: 'owner:jm' }).then(console.log).catch(console.log);`

If I can get it working I'll make a PR for it, but for now it's not working. :\

**Comment by wmoline** [comment]
Thanks for reporting this Jean-Martin!

It looks like the issue is coming from the RequestFactory where we append the token to the URL and then a few lines later stringify the body of the request. 

https://github.com/clubhouse/clubhouse-lib/blob/5eaf9f6d1dffcd71dd53f908e2c399efd26e4d0d/src/TokenRequestFactory.js#L13

That's not the approach we should be taking for GET requests. 

If that's something you'd like to take a stab at, we'd welcome a PR. Otherwise, we'll hoping to get one up later this week. You could also potentially work around it in the constructor if this is blocking work for you.

**Comment by eliperkins** [comment]
[`v0.4.1`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.4.1) should fix this issue
